
### Login admin
POST  http://localhost:3000/api/admin/login
Content-Type: application/json

{
    "email": "admin@admin.arg",
    "password": "passoword"
}

### Crear user admin con POST
POST http://localhost:3000/api/admin
Content-Type: application/json

{
    "id": 2,
   "email": "admin@admin.arg",
    "pword": "password",
    "role": "admin"
}