
### Login admin
POST  http://localhost:3000/api/login
Content-Type: application/json

{
    "email": "admin@admin.us",
    "password": "boss"
}


### Crear user admin con POST
POST http://localhost:3000/api/
Content-Type: application/json

{
    "id": 1,
   "email": "admin@admin.arg",
    "pword": "password",
    "role": "admin"
}