### Recuperar todos los blogs
GET http://localhost:3000/api/blogs

### Recuperar un blog por id
GET http://localhost:3000/api/blogs/5

### Crear una blog con POST
POST http://localhost:3000/api/blogs
Content-Type: application/json

{
    "titulo": "Testing 01",
    "fecha": "2023/12/26",
    "escritor": "Admin",
    "contenido": "Lorem ipsum dolor sit amet, consectetur adipiscing elit phasellus.",
    "imagen": "img.jpg" 
}

### Borrar blog
DELETE http://localhost:3000/api/blogs/17


### Actualizar blog  
PATCH  http://localhost:3000/api/blogs/18
Content-Type: application/json

{
    "titulo": "Testing update01",
    "fecha": "2023/12/26",
    "escritor": "AdminPro",
    "contenido": "Lorem ipsum dolor sit amet, consectetur adipiscing elit phasellus.",
    "imagen": "img.png" 
}