### Recuperar todos los vendedores
GET http://localhost:3000/api/vendedores

### Recuperar un vendedor por id
GET http://localhost:3000/api/vendedores/15

### Crear una vendedor con POST
POST http://localhost:3000/api/vendedores
Content-Type: application/json

{
    "nombre": "Leandro",
    "apellido": "Bazan",
    "telefono": 77787544,
    "email": "probazan@anonimo.us",
    "imagen": "maravillas4k.jpg"
}

### Borrar vendedor
DELETE http://localhost:3000/api/vendedores/20


### Actualizar vendedor  
PATCH  http://localhost:3000/api/vendedores/20
Content-Type: application/json

{
    "nombre": "FELIPE",
    "apellido": "EL JEFE",
    "telefono": 77787544,
    "email": "probazan@anonimo.us",
    "imagen": "maravillas4k.jpg"
}